@url = localhost/task_planner/src/php/api

GET {{url}}/tasks.php
Content-Type: application/json
###

POST {{url}}/tasks.php
Content-Type: application/json

{
  "content": "Testing PUT route"
}
###

PUT {{url}}/tasks.php
Content-Type: application/json

{
  "id": 3
}